# Generated by Django 2.2.17 on 2021-01-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProcesamientoDatos', '0004_analisiscluster'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PROC_Estudio',
            new_name='Procesamiento_Estudio',
        ),
    ]
