# Generated by Django 2.2.17 on 2021-01-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PROC_Estudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del Estudio')),
                ('categoriaEstudio', models.CharField(max_length=30, verbose_name='Categoria')),
                ('fechaEstudio', models.DateField(verbose_name='Fecha del Estudio')),
                ('clave_Estudio', models.IntegerField(verbose_name='ID de Estudio')),
                ('num_muestra', models.IntegerField(verbose_name='Numero de Muestra')),
                ('invResp', models.CharField(max_length=30, verbose_name='Investigador Responsable')),
                ('protocoloEstudio', models.CharField(max_length=30, verbose_name='Nombre del Protocolo')),
                ('clave_Protocolo', models.IntegerField(null=True, verbose_name='ID de Protocolo')),
                ('participanteEstudio', models.IntegerField(verbose_name='ID del Participante')),
                ('efectuado', models.BooleanField()),
            ],
        ),
    ]
