# Generated by Django 2.2.17 on 2021-01-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProcesamientoDatos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proc_estudio',
            name='efectuado',
        ),
        migrations.AddField(
            model_name='proc_estudio',
            name='anaPost',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Analisis de Postprocesamiento'),
        ),
        migrations.AddField(
            model_name='proc_estudio',
            name='anaPre',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Analisis de Preprocesamiento'),
        ),
        migrations.AddField(
            model_name='proc_estudio',
            name='efectuadoPost',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proc_estudio',
            name='efectuadoPre',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
