# Generated by Django 2.2.17 on 2021-01-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProcesamientoDatos', '0002_auto_20210121_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='metodosPostprocesamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreM_post', models.CharField(max_length=30, verbose_name='Nombre del Método')),
                ('clave_MetodoPost', models.IntegerField(verbose_name='ID del Metodo_post')),
                ('cfMetodoPost', models.CharField(max_length=30, verbose_name='Codigo Fuente del Metodo')),
            ],
        ),
        migrations.CreateModel(
            name='metodosPreprocesamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreM_pre', models.CharField(max_length=30, verbose_name='Nombre del Método')),
                ('clave_MetodoPre', models.IntegerField(verbose_name='ID del Metodo_pre')),
                ('cfMetodoPre', models.CharField(max_length=30, verbose_name='Codigo Fuente del Metodo')),
            ],
        ),
    ]
