# Generated by Django 2.2.17 on 2021-01-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProcesamientoDatos', '0005_auto_20210122_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='analisisEstadisticaDescriptiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAnalisisED', models.CharField(max_length=30, verbose_name='Nombre AED')),
                ('codigoAnalisisED', models.IntegerField(verbose_name='ID de AED')),
                ('cfAnalisisED', models.CharField(max_length=30, verbose_name='Codigo Fuente del AED')),
            ],
        ),
        migrations.CreateModel(
            name='analisisEstadisticaInferencial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAnalisisEI', models.CharField(max_length=30, verbose_name='Nombre AEI')),
                ('codigoAnalisisEI', models.IntegerField(verbose_name='ID de AEI')),
                ('cfAnalisisEI', models.CharField(max_length=30, verbose_name='Codigo Fuente del AEI')),
            ],
        ),
        migrations.CreateModel(
            name='Machine_LearningMetodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAnalisisML', models.CharField(max_length=30, verbose_name='Nombre AML')),
                ('codigoAnalisisML', models.IntegerField(verbose_name='ID de AML')),
                ('cfAnalisisML', models.CharField(max_length=30, verbose_name='Codigo Fuente del AML')),
            ],
        ),
    ]
