# Generated by Django 2.2.17 on 2021-01-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('categoriaEstudio', models.CharField(max_length=30)),
                ('fechaEstudio', models.DateField()),
                ('clave_Estudio', models.IntegerField()),
                ('num_muestra', models.IntegerField()),
                ('invResp', models.CharField(max_length=30)),
                ('protocoloEstudio', models.CharField(max_length=30)),
                ('participanteEstudio', models.IntegerField()),
                ('efectuado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Investigador_Clinico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fechaNac', models.DateField()),
                ('DNI', models.IntegerField()),
                ('MP', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tfno', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fechaNac', models.DateField()),
                ('DNI', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tfno', models.CharField(max_length=15)),
            ],
        ),
    ]
