# Generated by Django 2.2.17 on 2021-01-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTomaDatos', '0004_estudio_clave_protocolo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocoloClinico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocoloEstudio', models.CharField(max_length=30, verbose_name='Nombre del Protocolo')),
                ('clave_Protocolo', models.IntegerField(null=True, verbose_name='ID de Protocolo')),
                ('tipoInvestigacion', models.CharField(max_length=30, verbose_name='Tipo de Investigacion')),
                ('aceptadoDiseño_Metodológico', models.BooleanField(verbose_name='Aceptacion Diseño Metodológico')),
                ('fechaAceptacionDM', models.DateField(verbose_name='Fecha Diseño Metodológico')),
                ('aceptadoConsetimiento_Informado', models.BooleanField(verbose_name='Aceptacion Consentimiento Informado')),
                ('fechaAceptacionCI', models.DateField(verbose_name='Fecha Consentimiento Informado')),
                ('fechaInicioInvestigacion', models.DateField(verbose_name='Fecha Inicion de Investigacion')),
                ('investigadorResponsable1', models.CharField(max_length=30, verbose_name='Investigador Responsable 1- IR_1')),
                ('MP_IR1', models.IntegerField(verbose_name='Matricula Profesional IR_1')),
                ('investigadorResponsable2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Investigador Responsable 1- IR_2')),
                ('MP_IR2', models.IntegerField(blank=True, null=True, verbose_name='Matricula Profesional IR_2')),
            ],
        ),
    ]
