# Generated by Django 2.2.17 on 2021-01-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTomaDatos', '0007_auto_20210120_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocoloclinico',
            name='MP_IR3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Matricula Profesional IR_3'),
        ),
        migrations.AddField(
            model_name='protocoloclinico',
            name='investigadorResponsable3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Investigador Responsable 1- IR_3'),
        ),
        migrations.AlterField(
            model_name='protocoloclinico',
            name='tipoInvestigacion',
            field=models.CharField(max_length=150, verbose_name='Tipo de Investigacion'),
        ),
    ]
