# Generated by Django 2.2.17 on 2021-01-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTomaDatos', '0008_auto_20210120_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdqData_EEG_Protocolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Estudio')),
                ('estadoConciencia', models.CharField(max_length=50, verbose_name='Estado de Conciencia')),
                ('condicionFisica', models.CharField(max_length=50, verbose_name='Condicion Fisica')),
                ('estadoElectrofisiologico', models.CharField(max_length=150, verbose_name='Estado Electrofisiológico')),
                ('cantidad_EstadosElectrofisio', models.IntegerField(null=True, verbose_name='N° de Estados Electrofisiologicos')),
                ('duracion_Registro', models.IntegerField(null=True, verbose_name='Duracion del Registro')),
                ('numero_Canales', models.IntegerField(null=True, verbose_name='Numero de Canales')),
                ('sample_canales', models.IntegerField(null=True, verbose_name='Tasa de Muestreo')),
            ],
        ),
        migrations.AlterField(
            model_name='protocoloclinico',
            name='investigadorResponsable2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Investigador Responsable 2- IR_2'),
        ),
        migrations.AlterField(
            model_name='protocoloclinico',
            name='investigadorResponsable3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Investigador Responsable 3- IR_3'),
        ),
    ]
