# Generated by Django 2.2.17 on 2021-01-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTomaDatos', '0009_auto_20210120_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adqdata_eeg_protocolo',
            name='duracion_Registro',
            field=models.IntegerField(null=True, verbose_name='Duracion del Registro: min.'),
        ),
    ]
