# Generated by Django 2.2.17 on 2021-01-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTomaDatos', '0010_auto_20210120_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adqdata_eeg_protocolo',
            name='sample_canales',
            field=models.IntegerField(null=True, verbose_name='Tasa de Muestreo: Hz'),
        ),
    ]
