# Generated by Django 2.2.17 on 2021-01-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTomaDatos', '0002_auto_20210116_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='categoriaEstudio',
            field=models.CharField(max_length=30, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='clave_Estudio',
            field=models.IntegerField(verbose_name='ID de Estudio'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='fechaEstudio',
            field=models.DateField(verbose_name='Fecha del Estudio'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='invResp',
            field=models.CharField(max_length=30, verbose_name='Investigador Responsable'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre del Estudio'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='num_muestra',
            field=models.IntegerField(verbose_name='Numero de Muestra'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='participanteEstudio',
            field=models.IntegerField(verbose_name='ID del Participante'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='protocoloEstudio',
            field=models.CharField(max_length=30, verbose_name='Nombre del Protocolo'),
        ),
        migrations.AlterField(
            model_name='investigador_clinico',
            name='MP',
            field=models.IntegerField(verbose_name='Matricula Profesional'),
        ),
        migrations.AlterField(
            model_name='investigador_clinico',
            name='fechaNac',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='investigador_clinico',
            name='tfno',
            field=models.CharField(max_length=15, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='fechaNac',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='tfno',
            field=models.CharField(max_length=15, verbose_name='Telefono'),
        ),
    ]
