# Generated by Django 2.2.17 on 2021-01-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTomaDatos', '0003_auto_20210117_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='clave_Protocolo',
            field=models.IntegerField(null=True, verbose_name='ID de Protocolo'),
        ),
    ]
