# Generated by Django 2.2.17 on 2021-01-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTomaDatos', '0006_auto_20210120_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocoloclinico',
            name='protocoloEstudio',
            field=models.CharField(max_length=300, verbose_name='Nombre del Protocolo'),
        ),
    ]
