# Generated by Django 2.2.17 on 2021-01-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNeuroLab_Panel_de_Control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdqData_EEG_Protocolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Estudio')),
                ('estadoConciencia', models.CharField(max_length=50, verbose_name='Estado de Conciencia')),
                ('condicionFisica', models.CharField(max_length=50, verbose_name='Condicion Fisica')),
                ('estadoElectrofisiologico', models.CharField(max_length=150, verbose_name='Estado Electrofisiológico')),
                ('cantidad_EstadosElectrofisio', models.IntegerField(null=True, verbose_name='N° de Estados Electrofisiologicos')),
                ('duracion_Registro', models.IntegerField(null=True, verbose_name='Duracion del Registro: min.')),
                ('numero_Canales', models.IntegerField(null=True, verbose_name='Numero de Canales')),
                ('sample_canales', models.IntegerField(null=True, verbose_name='Tasa de Muestreo: Hz')),
                ('eegData', models.CharField(max_length=50, null=True, verbose_name='Raw Signals')),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del Estudio')),
                ('categoriaEstudio', models.CharField(max_length=30, verbose_name='Categoria')),
                ('fechaEstudio', models.DateField(verbose_name='Fecha del Estudio')),
                ('clave_Estudio', models.IntegerField(verbose_name='ID de Estudio')),
                ('num_muestra', models.IntegerField(verbose_name='Numero de Muestra')),
                ('invResp', models.CharField(max_length=30, verbose_name='Investigador Responsable')),
                ('protocoloEstudio', models.CharField(max_length=30, verbose_name='Nombre del Protocolo')),
                ('clave_Protocolo', models.IntegerField(null=True, verbose_name='ID de Protocolo')),
                ('participanteEstudio', models.IntegerField(verbose_name='ID del Participante')),
                ('efectuado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Investigador_Clinico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fechaNac', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('DNI', models.IntegerField()),
                ('MP', models.IntegerField(verbose_name='Matricula Profesional')),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tfno', models.CharField(max_length=15, verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fechaNac', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('DNI', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tfno', models.CharField(max_length=15, verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='ProtocoloClinico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocoloEstudio', models.CharField(max_length=300, verbose_name='Nombre del Protocolo')),
                ('clave_Protocolo', models.IntegerField(null=True, verbose_name='ID de Protocolo')),
                ('tipoInvestigacion', models.CharField(max_length=150, verbose_name='Tipo de Investigacion')),
                ('aceptadoDiseño_Metodológico', models.BooleanField(verbose_name='Aceptacion Diseño Metodológico')),
                ('fechaAceptacionDM', models.DateField(verbose_name='Fecha Diseño Metodológico')),
                ('aceptadoConsetimiento_Informado', models.BooleanField(verbose_name='Aceptacion Consentimiento Informado')),
                ('fechaAceptacionCI', models.DateField(verbose_name='Fecha Consentimiento Informado')),
                ('fechaInicioInvestigacion', models.DateField(verbose_name='Fecha Inicion de Investigacion')),
                ('investigadorResponsable1', models.CharField(max_length=30, verbose_name='Investigador Responsable 1- IR_1')),
                ('MP_IR1', models.IntegerField(verbose_name='Matricula Profesional IR_1')),
                ('investigadorResponsable2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Investigador Responsable 2- IR_2')),
                ('MP_IR2', models.IntegerField(blank=True, null=True, verbose_name='Matricula Profesional IR_2')),
                ('investigadorResponsable3', models.CharField(blank=True, max_length=30, null=True, verbose_name='Investigador Responsable 3- IR_3')),
                ('MP_IR3', models.IntegerField(blank=True, null=True, verbose_name='Matricula Profesional IR_3')),
            ],
        ),
    ]
