# Generated by Django 2.2.17 on 2021-01-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APP_TableroControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appsNombre', models.CharField(max_length=300, verbose_name='Nombre del APPs')),
                ('appsNumero', models.IntegerField(null=True, verbose_name='ID de APPs')),
            ],
        ),
    ]
