# Generated by Django 2.2.17 on 2021-01-21 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNeuroLab_Panel_de_Control', '0002_adqdata_eeg_protocolo_estudio_investigador_clinico_participantes_protocoloclinico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdqData_EEG_Protocolo',
        ),
        migrations.DeleteModel(
            name='Estudio',
        ),
        migrations.DeleteModel(
            name='Investigador_Clinico',
        ),
        migrations.DeleteModel(
            name='Participantes',
        ),
        migrations.DeleteModel(
            name='ProtocoloClinico',
        ),
    ]
