# Generated by Django 2.2.17 on 2021-01-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNeuroLab_Panel_de_Control', '0003_auto_20210121_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_tablerocontrol',
            name='appsBDcantidad',
            field=models.IntegerField(null=True, verbose_name='N°BD de la APPs'),
        ),
        migrations.AddField(
            model_name='app_tablerocontrol',
            name='appsBDnombres',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Bases de Datos de la APPs'),
        ),
    ]
