# Generated by Django 2.2.17 on 2021-01-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNeuroLab_Panel_de_Control', '0006_auto_20210129_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembroslab',
            name='miembImagen',
            field=models.ImageField(null=True, upload_to='gestionPanelControlmedia'),
        ),
    ]
