# Generated by Django 2.2.17 on 2021-02-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNeuroLab_Panel_de_Control', '0007_miembroslab_miembimagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiembrosLab',
        ),
        migrations.DeleteModel(
            name='VisitanteLab',
        ),
    ]
